[project]
name = "gildore-vault"

[toolchain]
type = "solana"

[testing]
language = "rust"
# framework = "quasarsvm-rust"

[testing.rust]
framework = "quasar-svm"

# [testing.typescript]
# framework = "quasar-svm"
# sdk = "kit"
# install = { program = "pnpm", args = ["install", "--frozen-lockfile"] }
# test = { program = "pnpm", args = ["vitest", "run"] }


[testing.rust.test]
program = "cargo"
args = ["test", "tests::"]

[clients]
path = "target/client"
languages = ["rust", "typescript"]
